name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          tags: nexus-term:latest
          outputs: type=docker,dest=/tmp/nexus-term.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nexus-term-image
          path: /tmp/nexus-term.tar
